name: surf_flutter_summer_school_24
description: "Surf Flutter Summer School '24"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  collection: ^1.18.0
  elementary: ^3.0.0
  elementary_helper: ^1.0.1
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/images/